# Generated by Django 4.1.7 on 2023-04-07 08:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
