# Generated by Django 4.2.3 on 2023-07-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='bolg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogo', to='blog.blogmodel'),
        ),
    ]
