# Generated by Django 4.1.7 on 2023-04-07 08:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
